# Generated by Django 2.2.6 on 2019-10-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
