# Generated by Django 2.2.6 on 2019-10-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
