# Generated by Django 2.2.6 on 2019-10-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='key',
            field=models.CharField(max_length=32),
        ),
    ]
